### PR TITLE
Styles for article and footer

### PR DESCRIPTION
**Pull request by adrifolio**
For #12 
Added the missing parts:

screen shot 2019-01-30 at 8 22 07 am

Also:
- Added responsiveness. @matthewp I'm stacking the demos at 900px or less as I felt this is as narrow as the demos could go (that would be 450 each), let me know if you think this works.
- Added accessibility tags

### CODE REVIEW

**Comment by adrifolio** [comment]
@matthewp I'm also missing two links:
- to the bitovi slack community
- to the velocirender channel on slack

**Comment by matthewp** [comment]
Looks great! Couple of things:

* Can we make the article display: none for now until it's ready to go?
* The slack channel is __#performance__. Link is here: https://bitovi-community.slack.com/messages/CFL3K9NHY/
* Bitovi Community: https://bitovi-community.slack.com/

**Comment by adrifolio** [comment]
Excellent @matthewp! The updates are in.

**Comment by matthewp** [comment]
Cool, thanks! One last thing (can merge this now and do later if you want), I think we're still missing a favicon.

**Comment by adrifolio** [comment]
Good catch! I will need to spend some time on that to get a crispy little favicon. I can do that tonight and plug it in tomorrow morning.

**Comment by matthewp** [comment]
Sounds good, created an issue to track: https://github.com/bitovi/velocirender/issues/40

**Pull request merged**
